### ISSUE TITLE
symlink ynh-dev in /usr/bin in the docker

### ISSUE THREAD

**Issue by Psycojoker** [YunoHost/ynh-dev#3]
I don't know if it's a good idea but that would quite practicle, so I'm opening this ticker this discuss that.

**Comment by zamentur** [comment]
It should be a good idea. The problem is the docker image can be run without ynh-dev...

**Comment by Psycojoker** [comment]
Modify bash PATH then? <code>[ -e "/path/to/ynh-dev" ] && PATH="/path/to/ynh-dev:"$PATH</code>
